[build-system]
requires = ["setuptools>=68", "setuptools_scm"]
build-backend = "setuptools.build_meta"

[project]
name = "Blu_easy_pygame"
dynamic = ["version"]
authors = [
  { name="Praneel Shanmugam", email="praneelcatchu@gmail.com" },
]
description = "a easier way to use pygames"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools_scm]
write_to = "src/easypygame/_version.py"
